/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author alepd
 */
public class VistaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VistaPrincipal
     */
    public VistaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenuMonitores = new javax.swing.JMenu();
        jMenuItemMonitores = new javax.swing.JMenuItem();
        jMenuItemCuotaMonitor = new javax.swing.JMenuItem();
        jMenuSocios = new javax.swing.JMenu();
        jMenuItemSocios = new javax.swing.JMenuItem();
        jMenuItemCuotaSocios = new javax.swing.JMenuItem();
        jMenuItemCambiarCategoriaSocio = new javax.swing.JMenuItem();
        jMenuActividades = new javax.swing.JMenu();
        jMenuItemActividades = new javax.swing.JMenuItem();
        jMenuItemCuotaActividad = new javax.swing.JMenuItem();
        jMenuSalir = new javax.swing.JMenu();
        jMenuItemSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestion del Gimnasio: \"Body Perfect\"");

        jMenuMonitores.setText("Monitores");

        jMenuItemMonitores.setText("Gestión de Monitores");
        jMenuItemMonitores.setActionCommand("GestionMonitores");
        jMenuMonitores.add(jMenuItemMonitores);

        jMenuItemCuotaMonitor.setText("Cuota de Monitor");
        jMenuItemCuotaMonitor.setActionCommand("CuotaMonitor");
        jMenuMonitores.add(jMenuItemCuotaMonitor);

        jMenuBar2.add(jMenuMonitores);

        jMenuSocios.setText("Socios");
        jMenuSocios.setActionCommand("GestionSocios");

        jMenuItemSocios.setText("Gestión de Socios");
        jMenuItemSocios.setActionCommand("GestionSocios");
        jMenuSocios.add(jMenuItemSocios);

        jMenuItemCuotaSocios.setText("Cuota de Socio");
        jMenuItemCuotaSocios.setActionCommand("CuotaSocio");
        jMenuSocios.add(jMenuItemCuotaSocios);

        jMenuItemCambiarCategoriaSocio.setText("Cambiar categoría socio");
        jMenuItemCambiarCategoriaSocio.setActionCommand("CambiarCategoriaSocio");
        jMenuItemCambiarCategoriaSocio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCambiarCategoriaSocioActionPerformed(evt);
            }
        });
        jMenuSocios.add(jMenuItemCambiarCategoriaSocio);

        jMenuBar2.add(jMenuSocios);

        jMenuActividades.setText("Actividades");

        jMenuItemActividades.setText("Socios por Actividad");
        jMenuItemActividades.setActionCommand("GestionActividades");
        jMenuActividades.add(jMenuItemActividades);

        jMenuItemCuotaActividad.setText("Cuota de Actividad");
        jMenuItemCuotaActividad.setActionCommand("CuotaActividad");
        jMenuActividades.add(jMenuItemCuotaActividad);

        jMenuBar2.add(jMenuActividades);

        jMenuSalir.setText("Salir");
        jMenuSalir.setActionCommand("SalirVentanaPrincipal");

        jMenuItemSalir.setText("Salir de la Aplicación");
        jMenuSalir.add(jMenuItemSalir);

        jMenuBar2.add(jMenuSalir);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 948, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 387, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemCambiarCategoriaSocioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCambiarCategoriaSocioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemCambiarCategoriaSocioActionPerformed

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenuActividades;
    private javax.swing.JMenuBar jMenuBar2;
    public javax.swing.JMenuItem jMenuItemActividades;
    public javax.swing.JMenuItem jMenuItemCambiarCategoriaSocio;
    public javax.swing.JMenuItem jMenuItemCuotaActividad;
    public javax.swing.JMenuItem jMenuItemCuotaMonitor;
    public javax.swing.JMenuItem jMenuItemCuotaSocios;
    public javax.swing.JMenuItem jMenuItemMonitores;
    public javax.swing.JMenuItem jMenuItemSalir;
    public javax.swing.JMenuItem jMenuItemSocios;
    public javax.swing.JMenu jMenuMonitores;
    public javax.swing.JMenu jMenuSalir;
    public javax.swing.JMenu jMenuSocios;
    // End of variables declaration//GEN-END:variables
}
