/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

/**
 *
 * @author alepd
 */
public class VistaSocio extends javax.swing.JPanel {

    /**
     * Creates new form VistaSocio
     */
    public VistaSocio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        botonNuevoSocio = new javax.swing.JButton();
        botonBajaSocio = new javax.swing.JButton();
        botonActualizarSocio = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableSocios = new javax.swing.JTable();
        botonBuscarSocio = new javax.swing.JButton();
        botonInscripcionesSocio = new javax.swing.JButton();
        botonNuevaInscripcion = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Bahnschrift", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Gestión de Socios");

        botonNuevoSocio.setText("Nuevo Socio");
        botonNuevoSocio.setActionCommand("VentanaNuevoSocio");

        botonBajaSocio.setText("Baja de Socio");
        botonBajaSocio.setActionCommand("BajaSocio");
        botonBajaSocio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBajaSocioActionPerformed(evt);
            }
        });

        botonActualizarSocio.setText("Actualizar Socio");
        botonActualizarSocio.setActionCommand("VentanaActualizarSocio");
        botonActualizarSocio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonActualizarSocioActionPerformed(evt);
            }
        });

        jTableSocios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "1", "2", "3", "4", "5", "6", "7", "8"
            }
        ));
        jScrollPane1.setViewportView(jTableSocios);

        botonBuscarSocio.setText("Buscar Socio");
        botonBuscarSocio.setActionCommand("VentanaBuscarSocio");

        botonInscripcionesSocio.setText("Ver/Borrar Inscripciones");
        botonInscripcionesSocio.setActionCommand("VentanaInscripcionesSocio");
        botonInscripcionesSocio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonInscripcionesSocioActionPerformed(evt);
            }
        });

        botonNuevaInscripcion.setText("Nueva Inscripcion");
        botonNuevaInscripcion.setActionCommand("VentanaNuevaInscripcion");
        botonNuevaInscripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonNuevaInscripcionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botonNuevoSocio)
                        .addGap(18, 18, 18)
                        .addComponent(botonBajaSocio)
                        .addGap(18, 18, 18)
                        .addComponent(botonActualizarSocio)
                        .addGap(18, 18, 18)
                        .addComponent(botonBuscarSocio, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(botonInscripcionesSocio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(botonNuevaInscripcion)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 794, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 56, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonNuevoSocio)
                    .addComponent(botonBajaSocio)
                    .addComponent(botonActualizarSocio)
                    .addComponent(botonBuscarSocio)
                    .addComponent(botonInscripcionesSocio)
                    .addComponent(botonNuevaInscripcion))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void botonBajaSocioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBajaSocioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonBajaSocioActionPerformed

    private void botonActualizarSocioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonActualizarSocioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonActualizarSocioActionPerformed

    private void botonInscripcionesSocioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonInscripcionesSocioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonInscripcionesSocioActionPerformed

    private void botonNuevaInscripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNuevaInscripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonNuevaInscripcionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton botonActualizarSocio;
    public javax.swing.JButton botonBajaSocio;
    public javax.swing.JButton botonBuscarSocio;
    public javax.swing.JButton botonInscripcionesSocio;
    public javax.swing.JButton botonNuevaInscripcion;
    public javax.swing.JButton botonNuevoSocio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable jTableSocios;
    // End of variables declaration//GEN-END:variables
}
