/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;
import Modelo.*;

/**
 *
 * @author alepd
 */
public class VistaMonitor extends javax.swing.JPanel {

    /**
     * Creates new form VistaMonitor
     */
    public VistaMonitor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        botonNuevoMonitor = new javax.swing.JButton();
        botonBajaMonitor = new javax.swing.JButton();
        botonActualizarMonitor = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableMonitores = new javax.swing.JTable();

        jLabel1.setFont(new java.awt.Font("Bahnschrift", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Gestión de Monitores");

        botonNuevoMonitor.setText("Nuevo Monitor");
        botonNuevoMonitor.setActionCommand("VentanaNuevoMonitor");

        botonBajaMonitor.setText("Baja de Monitor");
        botonBajaMonitor.setActionCommand("BajaMonitor");
        botonBajaMonitor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBajaMonitorActionPerformed(evt);
            }
        });

        botonActualizarMonitor.setText("Actualizar Monitor");
        botonActualizarMonitor.setActionCommand("VentanaActualizarMonitor");
        botonActualizarMonitor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonActualizarMonitorActionPerformed(evt);
            }
        });

        jTableMonitores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "1", "2", "3", "4", "5", "6", "7"
            }
        ));
        jScrollPane1.setViewportView(jTableMonitores);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botonNuevoMonitor)
                        .addGap(18, 18, 18)
                        .addComponent(botonBajaMonitor)
                        .addGap(18, 18, 18)
                        .addComponent(botonActualizarMonitor)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 968, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 17, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonNuevoMonitor)
                    .addComponent(botonBajaMonitor)
                    .addComponent(botonActualizarMonitor))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void botonBajaMonitorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBajaMonitorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonBajaMonitorActionPerformed

    private void botonActualizarMonitorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonActualizarMonitorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonActualizarMonitorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton botonActualizarMonitor;
    public javax.swing.JButton botonBajaMonitor;
    public javax.swing.JButton botonNuevoMonitor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable jTableMonitores;
    // End of variables declaration//GEN-END:variables
}
